baseURL = "http://sheas.blog/"
languageCode = "en-us"
title = "shea's blog"
theme = "tale"

# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = true
# pygmentsStyle = "monokai"

[Author]
    name = "Shea Newton"
