
baseurl = "/"
relativeURLs = true
theme = "cocoa-eh"
builddrafts = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Shea Newton"
title = "shea's blog"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
description = "This is the genre of art I make now."
og_image = "/img/space-2.png"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
copyright = "Copyright © 2017 Shea Newton"
copyrightUrl = "http://creativecommons.org/licenses/by-sa/4.0/"
logofile = "/img/space-2.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "shnewto"
email = "shnewto@gmail.com"
linkedin = "sheanewton"
twitter = "shnewto"
social_banner = ""
posts_navigation = true
small_banner_logo = false
latestpostcount = 5
